aliases: {soc: bf1_soc}
device:
  qubit:
    T1: [30, 30, 30]
    T2e: [60, 60, 60]
    T2r: [30, 30, 30]
    f_ef: [3800, 3800, 3800]
    f_ge: [2500, 3750, 3100]
    kappa: [0, 0, 0]
    low_gain: 0.003
    max_gain: 1
    pop: [0, 0, 0]
    pulses:
      pi_ef:
        gain: [0.15, 0.15, 0.15]
        sigma: [0.1, 0.1, 0.1]
        sigma_inc: [5, 5, 5]
        type: [gauss, gauss, gauss]
      pi_ge:
        gain: [0.15, 0.15, 0.15]
        sigma: [0.1, 0.1, 0.1]
        sigma_inc: [5, 5, 5]
        type: [gauss, gauss, gauss]
    spec_gain: [1, 1, 1]
    temp: [0, 0, 0]
    tuned_up: [false, false, false]
  readout:
    active_reset: [false, false, false]
    chi: [0, 0, 0]
    fidelity: [0, 0, 0]
    final_delay: [180, 180, 180]
    frequency: [5303.3908, 5833.6154, 6528.6491]
    gain: [0.03, 0.03, 0.03]
    kappa: [1.0096, 0.8317, 1.0836]
    lamb: [0, 0, 0]
    max_gain: 1
    phase: [0, 0, 0]
    qe: [1.6012, 1.5132, 1.2181]
    qi: [0.7818, 1.3074, 1.1923]
    readout_length: [5, 5, 5]
    reps: [1, 1, 1]
    reps_base: 150
    reset_e: [0, 0, 0]
    reset_g: [0, 0, 0]
    sigma: [0, 0, 0]
    soft_avgs: [1, 1, 1]
    soft_avgs_base: 1
    threshold: [10, 10, 10]
    tm: [0, 0, 0]
    trig_offset: [0.5, 0.5, 0.5]
hw:
  soc:
    adcs:
      readout:
        ch: [1, 1, 1]
    dacs:
      qubit:
        ch: [3, 3, 3]
        nyquist: [1, 1, 1]
        type: [full, full, full]
      readout:
        ch: [0, 0, 0]
        nyquist: [2, 2, 2]
        type: [full, full, full]
